"""Update QuizSubmission to reference username2

Revision ID: 5544adcb5b28
Revises: e3ef9b5029b0
Create Date: 2025-03-30 04:29:17.434748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5544adcb5b28'
down_revision: Union[str, None] = 'e3ef9b5029b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_submission', sa.Column('username', sa.String(length=150), nullable=True))
    op.drop_constraint('quiz_submission_user_username_fkey', 'quiz_submission', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_submission', 'member', ['username'], ['username'], ondelete='CASCADE')
    op.drop_column('quiz_submission', 'user_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_submission', sa.Column('user_username', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quiz_submission', type_='foreignkey')
    op.create_foreign_key('quiz_submission_user_username_fkey', 'quiz_submission', 'member', ['user_username'], ['username'], ondelete='CASCADE')
    op.drop_column('quiz_submission', 'username')
    # ### end Alembic commands ###
