"""Update QuizSubmission to reference username

Revision ID: e3ef9b5029b0
Revises: 8731b61877cd
Create Date: 2025-03-30 04:26:31.872632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ef9b5029b0'
down_revision: Union[str, None] = '8731b61877cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_submission', sa.Column('user_username', sa.String(length=150), nullable=True))
    op.create_foreign_key(None, 'quiz_submission', 'member', ['user_username'], ['username'], ondelete='CASCADE')
    op.drop_column('quiz_submission', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_submission', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quiz_submission', type_='foreignkey')
    op.drop_column('quiz_submission', 'user_username')
    # ### end Alembic commands ###
